[project]
authors = ["Aleksandra <137651489+aleksandra-maciruta@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Data_Wrangling"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
